apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: jenkins
  labels:
    app: myapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        apps: myapp
    spec:
      containers:
      - name: myapp
        image: mohamedji/myapp
        ports:
        - containerPort: 8080
