apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: jenkins
  labels:
    app: myapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        apps: myapp
    spec:
      containers:
      - name: myapp
        imagePullPolicy: Always
        image: mohamedji/myapp
        ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: jenkins
spec:
  ports:
    - name: http
      port: 8080
  type: NodePort   
  selector:
    apps: myapp
