apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: jenkins
  labels:
    app: myapp
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        apps: myapp
    spec:
      containers:
      - name: myapp
        imagePullPolicy: Always
        image: mohamedji/myapp:v4
        ports:
        - containerPort: 8080     
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: jenkins
spec:
  ports:
    - name: http
      port: 8080
  type: NodePort   
  selector:
    apps: myapp
